stages:
- stage: validate
  jobs:
  - job: validate
    continueOnError: false
    steps:
    - task: TerraformInstaller@0
      displayName: install
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV3@3
      displayName: init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'azure-spn'

    - task: TerraformTaskV3@3
      displayName: validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        backendServiceArm: 'azure-spn'
        
      
- stage: deploy
  jobs:
  - deployment: deploy_storage_account
    continueOnError: false
    environment: 'dev'
    strategy:
     runOnce:
       deploy:
        steps: 
          - checkout: self

          - task: TerraformInstaller@0
            displayName: 'install'
            inputs:
              terraformVersion: 'latest'
              backendServiceArm: 'azure-spn'

          - task: TerraformTaskV3@3
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'

          - task: TerraformTaskV3@3
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'

          - task: TerraformTaskV3@3
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'